### PR TITLE
Make build work on Windows

### LINKED ISSUE #59: Build error on Windows
I tried to run the installation of ContentaJS, which depends on plugnplay@3.5.0 on Windows.
During "npm install" execution I'm getting the following error.

> Try 'rm --help' for more information.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugnplay@3.5.0 build: `rm -fr lib; flow-remove-types --all src/ --out-dir lib/ && copy ./src/**/plugnplay.yml lib && flow-copy-source src lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plugnplay@3.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<----removed------>\Roaming\npm-cache\_logs\2019-02-05T13_33_45_149Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plugnplay@3.5.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plugnplay@3.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<----removed------>\AppData\Roaming\npm-cache\_logs\2019-02-05T13_33_55_995Z-debug.log

Looks like that `plugnplay` is not using the `rimraf` module but  the UNIX `rm` command also on Windows.

### PR DESCRIPTION
**Pull request by jdoxley**
Change the `rm -rf` in the build script with `rimraf`. This should fix #59.

### CODE REVIEW

**Comment by e0ipso** [comment]
Yes! I have been meaning to do that same change for a while. Thanks for the contribution.

**Comment by Revadike** [comment]
I keep getting this
image

I also tried earlier versions, but that also didn't work.

**Comment by Revadike** [comment]
The problem is this part of the command: `copy ./src/**/plugnplay.yml lib`

**Comment by e0ipso** [comment]
@Revadike did you figure it out?

**Comment by Revadike** [comment]
No

**Pull request merged**
